FROM ubuntu:latest

RUN apt-get update && apt-get -y upgrade && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    apache2 php7.0 php7.0-mysql libapache2-mod-php7.0 curl lynx-cur
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install mysql-server	

RUN docker-php-ext-install pdo pdo_mysql gd curl

 
RUN a2enmod php7.0
RUN a2enmod rewrite
RUN a2enmod ssl


RUN mkdir /var/www/armbook
VOLUME /Users/Isaac/Documents/Homework5/www:/var/www/armbook
ADD www /var/www/armbook
ADD apache-config.conf /etc/apache2/sites-enabled/000-default.conf
COPY server.crt /etc/apache2/ssl/server.crt
COPY server.key /etc/apache2/ssl/server.key
COPY dev.conf /etc/apache2/sites-enabled/dev.conf

ENV APACHE_RUN_USER user
ENV APACHE_RUN_GROUP www
ENV APACHE_LOG_DIR /var/log/apache2


RUN service apache2 restart
EXPOSE 80
EXPOSE 8080
EXPOSE 443


RUN echo "ServerName localhost" >> /etc/apache2/httpd.cof
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf


CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
